steps:

  # Build da imagem
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/extrator-sinasc'
      - '.'

  # Executa o container
  - name: 'gcr.io/$PROJECT_ID/extrator-sinasc'
    id: 'run-extraction'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s