steps:
  # Passo 1: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oda-natalidade-job:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/oda-natalidade-job:latest', '.']

  # Passo 2: Enviar a imagem para o registro com a tag do Commit
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oda-natalidade-job:$COMMIT_SHA']

  # Passo 3: Enviar a imagem para o registro com a tag Latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oda-natalidade-job:latest']

options:
  logging: CLOUD_LOGGING_ONLY